#!/usr/bin/zsh

setopt prompt_subst

NEWLINE=$'\n'
DOLLAR=$'$'
LBRACK=$'['
T_RES=$'%{\033[0m%}'

function cl () {
	echo "%{\033[$1m%}"
}

function get_git_branch() {
    GIT=$(git branch --show-current 2>/dev/null)
    if [[ -n $GIT ]]; then
      echo " %{\033[3m%}%F{11}:$GIT%f%{\033[0m%}"
    fi
}

function get_virtualenv() {
    if [[ -n $VIRTUAL_ENV ]]; then
      VENV=$(basename $VIRTUAL_ENV)
      echo "\033[3m%}%F{2}$VENV%f%{\033[0m%} » "
    fi
}

function get_hostname() {
	HOSTNAME=$(hostname)
	if [[ $COLUMNS -ge 70 ]]; then
		echo -e "%F{7}%f@%F{2}${HOSTNAME[@]:0:$1}%f"
	else
		echo -n ""
	fi
}

#***********************************************************************************************************************
function precmd() {
  STAT="$?"
  EXITC="%(?..%F{9}-%?-%f$NEWLINE)"
  PROMPT='$EXITC$NEWLINE┌$(get_virtualenv)%F{10}%B%n%b%f$(get_hostname 10) %F{15}%~%f$(get_git_branch)'
  RPROMPT=''
  PROMPT="$PROMPT$NEWLINE└%F{10}%D{%H:%M}%f%(!.#.%B%%%b) "
}
